/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.MyActionListener;
import driverClasses.GUI;
import enumClasses.tileType;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import mainClasses.cell;

/**
 *
 * @author SNaKeRUBIN
 */
public class GUI_AUTO extends javax.swing.JFrame {

    /**
     * Creates new form GUI_AUTO
     */
    public GUI_AUTO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        editPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setRollover(true);

        jButton1.setText("NEW");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuBar.add(jButton1);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_AUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_AUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_AUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_AUTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        int x = 10;
        int y = 10;

        cell[][] map = new cell[x][y];

        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                map[i][j] = new cell();

                if (i == j) {
                    map[i][j].type = tileType.CHEST;
                }
            }
        }

        GUI_AUTO gui = new GUI_AUTO();
        gui.makeGUI(map);
        gui.menuBar.setFloatable(false);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                gui.pack();
                gui.setVisible(true);
            }
        });
    }

    public void makeGUI(cell[][] map) {
        int x = map.length;
        int y = map[0].length;

        JButton[][] matrix = new JButton[x][y];

        Insets buttonMargin = new Insets(0, 0, 0, 0);
        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                JButton b = new JButton();
                b.putClientProperty("row", i);
                b.putClientProperty("column", j);
                b.setText("(" + b.getClientProperty("row") + ", " + b.getClientProperty("column") + ")");
                b.setMargin(buttonMargin);
                b.addActionListener(new MyActionListener());
                b.setIcon(null);

                b.setBackground(Color.LIGHT_GRAY);
                matrix[i][j] = b;
            }
        }

        displayPanel.setLayout(new BorderLayout());
        displayPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
        displayPanel.setAlignmentX(CENTER_ALIGNMENT);
        displayPanel.setAlignmentY(CENTER_ALIGNMENT);
        JPanel board = new JPanel(new GridLayout(0, y));
        board.setAlignmentX(CENTER_ALIGNMENT);
        board.setBorder(new CompoundBorder(
                new EmptyBorder(8, 8, 8, 8),
                new LineBorder(Color.WHITE)
        ));
        board.setBackground(Color.black);

        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                board.add(matrix[i][j]);
            }
        }

        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                cell temp = map[i][j];

                switch (temp.type) {

                    case EMPTY:
                        matrix[i][j].setBackground(Color.LIGHT_GRAY);
                        break;
                    case CHARCTER:
                        matrix[i][j].setBackground(Color.GREEN);
                        break;
                    case WALL:
                        matrix[i][j].setBackground(Color.RED);
                        break;
                    case CHEST:
                        matrix[i][j].setBackground(Color.yellow);
                        break;
                }
            }
        }

        //displayPanel.add(new JLabel("Heading"), BorderLayout.PAGE_START);
        //displayPanel.add(board, BorderLayout.EAST);
        //displayPanel.add(board, BorderLayout.WEST);
        //displayPanel.add(board, BorderLayout.NORTH);
        //displayPanel.add(board, BorderLayout.SOUTH);
        displayPanel.add(board, BorderLayout.CENTER);

        Dimension d = board.getParent().getSize();
        board.setSize(d);
        //        displayPanel.setSize(this.getParent().getSize());
        //displayPanel.add(new JButton(), BorderLayout.LINE_END);
        /*
        JFrame frame = new JFrame("Demo 1");

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.add(displayPanel);
        frame.setMinimumSize(new Dimension(300, 300));

        frame.pack();

        frame.setVisible(true);*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar menuBar;
    // End of variables declaration//GEN-END:variables
}
