package view;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import panels.mapEditorDimensions;
import panels.charcterEditorMain;
import panels.itemEditorMain;
import panels.mapEditorMain;
import mainClasses.character;
import mainClasses.campaign;
import mainClasses.item;
import mainClasses.map;

/**
 *
 * @author SNaKeRUBIN
 */
public class Main_Frame extends javax.swing.JFrame {

    CardLayout cardlayout;
    ArrayList<character> characterList;
    ArrayList<campaign> campaignList;
    ArrayList<map> mapList;
    HashMap<String, ArrayList<item>> itemList = new HashMap<>();

    //charcterEditorMain chrct;
    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
        pnlTopContainer.setVisible(false);
        pnlTopContainer.add(new charcterEditorMain(), "card1");
        pnlTopContainer.add(new itemEditorMain(), "card2");
        pnlTopContainer.add(new mapEditorMain(), "card3");
        //pnlTopContainer.add(new charcterEditorMain(), "card4");
        cardlayout = (CardLayout) pnlTopContainer.getLayout();

        loadCharacters();
        loadMaps();
        loadCampaign();
        loadItems();

        System.out.println("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopContainer = new javax.swing.JPanel();
        menubar_main_frame = new javax.swing.JMenuBar();
        menu_mainframe_Play = new javax.swing.JMenu();
        menu_mainframe_play_new = new javax.swing.JMenuItem();
        menu_mainframe_play_save = new javax.swing.JMenuItem();
        menu_mainframe_play_load = new javax.swing.JMenuItem();
        menu_mainframe_Editor = new javax.swing.JMenu();
        menu_mainframe_editor_char = new javax.swing.JMenuItem();
        menu_mainframe_editor_item = new javax.swing.JMenuItem();
        menu_mainframe_editor_map = new javax.swing.JMenuItem();
        menu_mainframe_editor_campaign = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTopContainer.setLayout(new java.awt.CardLayout());

        menu_mainframe_Play.setText("Play");

        menu_mainframe_play_new.setText("New");
        menu_mainframe_Play.add(menu_mainframe_play_new);

        menu_mainframe_play_save.setText("Save");
        menu_mainframe_Play.add(menu_mainframe_play_save);

        menu_mainframe_play_load.setText("Load");
        menu_mainframe_Play.add(menu_mainframe_play_load);

        menubar_main_frame.add(menu_mainframe_Play);

        menu_mainframe_Editor.setText("Editor");

        menu_mainframe_editor_char.setText("Character");
        menu_mainframe_editor_char.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mainframe_editor_charActionPerformed(evt);
            }
        });
        menu_mainframe_Editor.add(menu_mainframe_editor_char);

        menu_mainframe_editor_item.setText("Item");
        menu_mainframe_editor_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mainframe_editor_itemActionPerformed(evt);
            }
        });
        menu_mainframe_Editor.add(menu_mainframe_editor_item);

        menu_mainframe_editor_map.setText("Map");
        menu_mainframe_editor_map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mainframe_editor_mapActionPerformed(evt);
            }
        });
        menu_mainframe_Editor.add(menu_mainframe_editor_map);

        menu_mainframe_editor_campaign.setText("Campaign");
        menu_mainframe_Editor.add(menu_mainframe_editor_campaign);

        menubar_main_frame.add(menu_mainframe_Editor);

        setJMenuBar(menubar_main_frame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTopContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_mainframe_editor_charActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mainframe_editor_charActionPerformed
        pnlTopContainer.setVisible(true);
        cardlayout.show(pnlTopContainer, "card1");

        // TODO add your handling code here:
    }//GEN-LAST:event_menu_mainframe_editor_charActionPerformed

    private void menu_mainframe_editor_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mainframe_editor_itemActionPerformed
        pnlTopContainer.setVisible(true);
        cardlayout.show(pnlTopContainer, "card2");
// TODO add your handling code here:
    }//GEN-LAST:event_menu_mainframe_editor_itemActionPerformed

    private void menu_mainframe_editor_mapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mainframe_editor_mapActionPerformed
        pnlTopContainer.setVisible(true);
        cardlayout.show(pnlTopContainer, "card3");
// TODO add your handling code here:
    }//GEN-LAST:event_menu_mainframe_editor_mapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);

            }
        });
    }

    public void loadCharacters() {
        ObjectInputStream ois = null;
        try {
            File inputCharacters = new File("D:\\_character.txt");
            ois = new ObjectInputStream(new FileInputStream(inputCharacters));
            characterList = (ArrayList<character>) ois.readObject();
        } catch (IOException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void loadItems() {
        ObjectInputStream ois = null;
        try {
            File inputMaps = new File("D:\\_item.txt");
            ois = new ObjectInputStream(new FileInputStream(inputMaps));
            itemList = (HashMap<String, ArrayList<item>>) ois.readObject();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }

    }

    public void loadMaps() {
        ObjectInputStream ois = null;
        try {
            File inputMaps = new File("D:\\_maps.txt");
            ois = new ObjectInputStream(new FileInputStream(inputMaps));
            mapList = (ArrayList<map>) ois.readObject();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void loadCampaign() {
        ObjectInputStream ois = null;
        try {
            File inputCampaign = new File("D:\\_campaign.txt");
            ois = new ObjectInputStream(new FileInputStream(inputCampaign));
            campaignList = (ArrayList<campaign>) ois.readObject();
        } catch (IOException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menu_mainframe_Editor;
    private javax.swing.JMenu menu_mainframe_Play;
    private javax.swing.JMenuItem menu_mainframe_editor_campaign;
    private javax.swing.JMenuItem menu_mainframe_editor_char;
    private javax.swing.JMenuItem menu_mainframe_editor_item;
    private javax.swing.JMenuItem menu_mainframe_editor_map;
    private javax.swing.JMenuItem menu_mainframe_play_load;
    private javax.swing.JMenuItem menu_mainframe_play_new;
    private javax.swing.JMenuItem menu_mainframe_play_save;
    private javax.swing.JMenuBar menubar_main_frame;
    private javax.swing.JPanel pnlTopContainer;
    // End of variables declaration//GEN-END:variables
}
