/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.campaign;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reza
 */
public class Campaign_2 extends javax.swing.JFrame {

    /**
     * Creates new form Campaign_2
     */
    public Campaign_2() {
        initComponents();
        
        fillCombo();
        fillTable();
    }
/**
 * this method fill the Campaign combobox with the default Campaign and map values
 * 
 */    
    private void fillCombo(){
        ArrayList<String> arr = new ArrayList<String>();
        
        File file = new File("Input\\Campains.txt");
        
        try {
            Scanner input = new Scanner(file);
            while (input.hasNext()) {
                String next = input.next();
                arr.add(next);
                System.out.print(next);
            }
        } catch (FileNotFoundException e) {
            System.err.format("File does not exist.\n");
        }
        
        DefaultComboBoxModel model = new DefaultComboBoxModel(arr.toArray());
        
        cmbCampaign.setModel(model);
    }
/**
 * this method fill the Campaign table with the default Campaign and map values
 */    
    private void fillTable(){
        
        
        File file = new File("Input\\CampaignsMaps.txt");
        String line = null;
        DefaultTableModel dtm = (DefaultTableModel) tblCampaign.getModel();

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));

            while ((line = br.readLine()) != null) {
                Vector data = new Vector();// this is important
                StringTokenizer st1 = new StringTokenizer(line, ",");
                
                if (!st1.nextToken().equals(cmbCampaign.getSelectedItem().toString())) {
                    continue;
                }
                
                
                while (st1.hasMoreTokens()) {
                    
                    String nextToken = st1.nextToken();
                    
                    if (nextToken.equals(cmbCampaign.getSelectedItem().toString())) {
                        continue;
                    }
//                    if(!nextToken.equals(cmbCampaign.getSelectedItem().toString())) {
//                        DefaultTableModel dm = (DefaultTableModel)tblCampaign.getModel();
//                        dm.getDataVector().removeAllElements();
//                        //continue;
//                    }
                    
                    if (nextToken.equalsIgnoreCase("true")) {
                        data.add(true);
                    } else if (nextToken.equalsIgnoreCase("false")) {
                        data.add(false);
                    } else{
                        data.add(nextToken);
                    }
                        
                    
                    System.out.println(nextToken);

                }
                
                
                
                System.out.println(data);
                dtm.addRow(data);//add here 
                System.out.println(".................................");
               
            }
                
            br.close();
             
        } catch (Exception e) {
            e.printStackTrace();
        }
                
    }
    
    /**
     * this method save the changes in the related file
     */
    public void saveTable()throws Exception
        {
          BufferedWriter bfw = new BufferedWriter(new FileWriter("Input\\Data.txt"));
          for(int i = 0 ; i < tblCampaign.getColumnCount() ; i++)
          {
            bfw.write(tblCampaign.getColumnName(i));
            bfw.write("\t");
          }

          for (int i = 0 ; i < tblCampaign.getRowCount(); i++)
          {
            bfw.newLine();
            for(int j = 0 ; j < tblCampaign.getColumnCount();j++)
            {
              bfw.write((String)(tblCampaign.getValueAt(i,j)));
              bfw.write("\t");
            }
          }
          bfw.close();
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCampaign = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbCampaign = new javax.swing.JComboBox<>();
        saveTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCampaign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Map Name", "Order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCampaign);

        jLabel1.setText("Campaign:");

        cmbCampaign.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCampaignItemStateChanged(evt);
            }
        });
        cmbCampaign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCampaignMouseClicked(evt);
            }
        });

        saveTable.setText("Save");
        saveTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCampaign, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveTable))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCampaign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveTable))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCampaignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCampaignMouseClicked
        fillCombo();
    }//GEN-LAST:event_cmbCampaignMouseClicked

    private void cmbCampaignItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCampaignItemStateChanged
        DefaultTableModel dm = (DefaultTableModel)tblCampaign.getModel();
        dm.getDataVector().removeAllElements();
        fillTable();
    }//GEN-LAST:event_cmbCampaignItemStateChanged

    private void saveTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTableActionPerformed
      
//            saveTable();
        
    }//GEN-LAST:event_saveTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Campaign_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Campaign_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Campaign_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Campaign_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Campaign_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCampaign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveTable;
    private javax.swing.JTable tblCampaign;
    // End of variables declaration//GEN-END:variables
}
