/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author SNaKeRUBIN
 */
public class charcterEditorMain extends javax.swing.JPanel {

    /**
     * Creates new form charcterEditorMain
     */
    public charcterEditorMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControlPanel = new javax.swing.JPanel();
        button_new = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        DisplayPanel = new javax.swing.JPanel();
        label_image = new javax.swing.JLabel();
        label_helmet = new javax.swing.JLabel();
        combobox_helmet = new javax.swing.JComboBox<>();
        label_weapon = new javax.swing.JLabel();
        combobox_weapon = new javax.swing.JComboBox<>();
        label_shield = new javax.swing.JLabel();
        combobox_shield = new javax.swing.JComboBox<>();
        label_ring = new javax.swing.JLabel();
        combobox_ring = new javax.swing.JComboBox<>();
        label_belt = new javax.swing.JLabel();
        combobox_belt = new javax.swing.JComboBox<>();
        label_armour = new javax.swing.JLabel();
        combobox_armor = new javax.swing.JComboBox<>();
        label_boots = new javax.swing.JLabel();
        combobox_boots = new javax.swing.JComboBox<>();
        label_inv_1 = new javax.swing.JLabel();
        combobox_inv_1 = new javax.swing.JComboBox<>();
        label_inv_6 = new javax.swing.JLabel();
        combobox_inv_6 = new javax.swing.JComboBox<>();
        label_inv_2 = new javax.swing.JLabel();
        combobox_inv_2 = new javax.swing.JComboBox<>();
        label_inv_3 = new javax.swing.JLabel();
        combobox_inv_3 = new javax.swing.JComboBox<>();
        label_inv_4 = new javax.swing.JLabel();
        combobox_inv_4 = new javax.swing.JComboBox<>();
        label_inv_5 = new javax.swing.JLabel();
        combobox_inv_5 = new javax.swing.JComboBox<>();
        label_inv_7 = new javax.swing.JLabel();
        combobox_inv_7 = new javax.swing.JComboBox<>();
        label_inv_8 = new javax.swing.JLabel();
        combobox_inv_8 = new javax.swing.JComboBox<>();
        label_inv_9 = new javax.swing.JLabel();
        combobox_inv_9 = new javax.swing.JComboBox<>();
        label_inv_10 = new javax.swing.JLabel();
        combobox_inv_10 = new javax.swing.JComboBox<>();
        SelectPanel = new javax.swing.JPanel();
        label_name = new javax.swing.JLabel();
        label_lvl = new javax.swing.JLabel();
        textfield_name = new javax.swing.JTextField();
        combobox_lvl = new javax.swing.JComboBox<>();
        label_str = new javax.swing.JLabel();
        label_consti = new javax.swing.JLabel();
        label_intelli = new javax.swing.JLabel();
        label_dex = new javax.swing.JLabel();
        label_wis = new javax.swing.JLabel();
        label_charis = new javax.swing.JLabel();
        textfield_str = new javax.swing.JTextField();
        textfield_consti = new javax.swing.JTextField();
        textfield_intelli = new javax.swing.JTextField();
        textfield_dex = new javax.swing.JTextField();
        textfield_wis = new javax.swing.JTextField();
        textfield_charis = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_randomize = new javax.swing.JButton();

        button_new.setText("New");

        button_edit.setText("Edit");

        button_delete.setText("Delete");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_new)
                .addGap(74, 74, 74)
                .addComponent(button_edit)
                .addGap(95, 95, 95)
                .addComponent(button_delete)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_new)
                    .addComponent(button_edit)
                    .addComponent(button_delete))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        label_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CharcterTemplate.jpg"))); // NOI18N

        label_helmet.setText("Helmet");

        combobox_helmet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_weapon.setText("Weapon");

        combobox_weapon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_shield.setText("Shield");

        combobox_shield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_ring.setText("ring");

        combobox_ring.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_belt.setText("Belt");

        combobox_belt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_armour.setText("armor");

        combobox_armor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_boots.setText("boots");

        combobox_boots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_1.setText("Inventory 1");

        combobox_inv_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_6.setText("Inventory 6");

        combobox_inv_6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_2.setText("Inventory 2");

        combobox_inv_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_3.setText("Inventory 3");

        combobox_inv_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_4.setText("Inventory 4");

        combobox_inv_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_5.setText("Inventory 5");

        combobox_inv_5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_7.setText("Inventory 7");

        combobox_inv_7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_8.setText("Inventory 8");

        combobox_inv_8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_9.setText("Inventory 9");

        combobox_inv_9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_10.setText("Inventory 10");

        combobox_inv_10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(label_helmet)
                        .addGap(53, 53, 53)
                        .addComponent(combobox_helmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_weapon)
                            .addComponent(combobox_weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_armour)
                            .addComponent(combobox_armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_boots)
                            .addComponent(combobox_boots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(label_image)
                        .addGap(83, 83, 83)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_shield)
                            .addComponent(combobox_shield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ring)
                            .addComponent(combobox_ring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_belt)
                            .addComponent(combobox_belt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_inv_6)
                            .addComponent(label_inv_1))
                        .addGap(34, 34, 34)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combobox_inv_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_inv_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_inv_2)
                            .addComponent(label_inv_7))
                        .addGap(37, 37, 37)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(combobox_inv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(label_inv_3))
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(combobox_inv_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_inv_8)))
                        .addGap(31, 31, 31)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combobox_inv_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_inv_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_inv_4)
                            .addComponent(label_inv_9))
                        .addGap(44, 44, 44)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox_inv_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_inv_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(label_inv_5)
                                .addGap(18, 18, 18)
                                .addComponent(combobox_inv_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(label_inv_10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_inv_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_helmet)
                    .addComponent(combobox_helmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_image))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(label_shield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_shield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(label_ring)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_ring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(label_belt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_belt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(label_weapon)
                        .addGap(18, 18, 18)
                        .addComponent(combobox_weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(label_armour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(label_boots)
                        .addGap(18, 18, 18)
                        .addComponent(combobox_boots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_inv_1)
                    .addComponent(combobox_inv_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_2)
                    .addComponent(combobox_inv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_3)
                    .addComponent(combobox_inv_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_4)
                    .addComponent(combobox_inv_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_5)
                    .addComponent(combobox_inv_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_inv_6)
                    .addComponent(combobox_inv_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_7)
                    .addComponent(combobox_inv_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_8)
                    .addComponent(combobox_inv_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_9)
                    .addComponent(combobox_inv_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_10)
                    .addComponent(combobox_inv_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        label_name.setText("Name");

        label_lvl.setText("Level");

        textfield_name.setText("jTextField1");

        combobox_lvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_str.setText("Strength");

        label_consti.setText("Constitution");

        label_intelli.setText("Intelligence");

        label_dex.setText("Dexterity");

        label_wis.setText("Wisdom");

        label_charis.setText("Charisma");

        textfield_str.setText("jTextField1");

        textfield_consti.setText("jTextField2");

        textfield_intelli.setText("jTextField3");

        textfield_dex.setText("jTextField4");

        textfield_wis.setText("jTextField5");

        textfield_charis.setText("jTextField6");

        button_save.setText("Save");

        button_randomize.setText("Randomize");

        javax.swing.GroupLayout SelectPanelLayout = new javax.swing.GroupLayout(SelectPanel);
        SelectPanel.setLayout(SelectPanelLayout);
        SelectPanelLayout.setHorizontalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(SelectPanelLayout.createSequentialGroup()
                                    .addComponent(label_lvl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combobox_lvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SelectPanelLayout.createSequentialGroup()
                                    .addComponent(label_name)
                                    .addGap(41, 41, 41)
                                    .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SelectPanelLayout.createSequentialGroup()
                                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(SelectPanelLayout.createSequentialGroup()
                                        .addComponent(label_intelli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textfield_intelli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectPanelLayout.createSequentialGroup()
                                        .addComponent(label_consti)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textfield_consti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectPanelLayout.createSequentialGroup()
                                        .addComponent(label_str)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textfield_str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SelectPanelLayout.createSequentialGroup()
                                        .addComponent(label_charis)
                                        .addGap(18, 18, 18)
                                        .addComponent(textfield_charis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(SelectPanelLayout.createSequentialGroup()
                                            .addComponent(label_wis)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textfield_wis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(SelectPanelLayout.createSequentialGroup()
                                            .addComponent(label_dex)
                                            .addGap(18, 18, 18)
                                            .addComponent(textfield_dex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(SelectPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(button_randomize))))
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(button_save)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        SelectPanelLayout.setVerticalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lvl)
                    .addComponent(combobox_lvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_str)
                    .addComponent(label_dex)
                    .addComponent(textfield_str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_dex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_consti)
                    .addComponent(label_wis)
                    .addComponent(textfield_consti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_wis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_intelli)
                    .addComponent(label_charis)
                    .addComponent(textfield_intelli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_charis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(button_randomize)
                .addGap(134, 134, 134)
                .addComponent(button_save)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SelectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JPanel SelectPanel;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_new;
    private javax.swing.JButton button_randomize;
    private javax.swing.JButton button_save;
    private javax.swing.JComboBox<String> combobox_armor;
    private javax.swing.JComboBox<String> combobox_belt;
    private javax.swing.JComboBox<String> combobox_boots;
    private javax.swing.JComboBox<String> combobox_helmet;
    private javax.swing.JComboBox<String> combobox_inv_1;
    private javax.swing.JComboBox<String> combobox_inv_10;
    private javax.swing.JComboBox<String> combobox_inv_2;
    private javax.swing.JComboBox<String> combobox_inv_3;
    private javax.swing.JComboBox<String> combobox_inv_4;
    private javax.swing.JComboBox<String> combobox_inv_5;
    private javax.swing.JComboBox<String> combobox_inv_6;
    private javax.swing.JComboBox<String> combobox_inv_7;
    private javax.swing.JComboBox<String> combobox_inv_8;
    private javax.swing.JComboBox<String> combobox_inv_9;
    private javax.swing.JComboBox<String> combobox_lvl;
    private javax.swing.JComboBox<String> combobox_ring;
    private javax.swing.JComboBox<String> combobox_shield;
    private javax.swing.JComboBox<String> combobox_weapon;
    private javax.swing.JLabel label_armour;
    private javax.swing.JLabel label_belt;
    private javax.swing.JLabel label_boots;
    private javax.swing.JLabel label_charis;
    private javax.swing.JLabel label_consti;
    private javax.swing.JLabel label_dex;
    private javax.swing.JLabel label_helmet;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_intelli;
    private javax.swing.JLabel label_inv_1;
    private javax.swing.JLabel label_inv_10;
    private javax.swing.JLabel label_inv_2;
    private javax.swing.JLabel label_inv_3;
    private javax.swing.JLabel label_inv_4;
    private javax.swing.JLabel label_inv_5;
    private javax.swing.JLabel label_inv_6;
    private javax.swing.JLabel label_inv_7;
    private javax.swing.JLabel label_inv_8;
    private javax.swing.JLabel label_inv_9;
    private javax.swing.JLabel label_lvl;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_ring;
    private javax.swing.JLabel label_shield;
    private javax.swing.JLabel label_str;
    private javax.swing.JLabel label_weapon;
    private javax.swing.JLabel label_wis;
    private javax.swing.JTextField textfield_charis;
    private javax.swing.JTextField textfield_consti;
    private javax.swing.JTextField textfield_dex;
    private javax.swing.JTextField textfield_intelli;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_str;
    private javax.swing.JTextField textfield_wis;
    // End of variables declaration//GEN-END:variables
}
