/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mainClasses.character;

/**
 *
 * @author SNaKeRUBIN
 */
public class charcterEditorMain extends javax.swing.JPanel {

    ArrayList<character> characterList;
    character currentChar;

    /**
     * Creates new form charcterEditorMain
     */
    public charcterEditorMain(ArrayList<character> new_characterList) {
        initComponents();
        characterList = new_characterList;
        DisplayPanel.setVisible(false);
        SelectPanel.setVisible(false);
        button_delete.setEnabled(false);

        System.out.println("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControlPanel = new javax.swing.JPanel();
        button_new = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayPanel = new javax.swing.JPanel();
        label_image = new javax.swing.JLabel();
        label_helmet = new javax.swing.JLabel();
        combobox_helmet = new javax.swing.JComboBox<>();
        label_weapon = new javax.swing.JLabel();
        combobox_weapon = new javax.swing.JComboBox<>();
        label_shield = new javax.swing.JLabel();
        combobox_shield = new javax.swing.JComboBox<>();
        label_ring = new javax.swing.JLabel();
        combobox_ring = new javax.swing.JComboBox<>();
        label_belt = new javax.swing.JLabel();
        combobox_belt = new javax.swing.JComboBox<>();
        label_armour = new javax.swing.JLabel();
        combobox_armor = new javax.swing.JComboBox<>();
        label_boots = new javax.swing.JLabel();
        combobox_boots = new javax.swing.JComboBox<>();
        label_inv_1 = new javax.swing.JLabel();
        combobox_inv_1 = new javax.swing.JComboBox<>();
        label_inv_6 = new javax.swing.JLabel();
        combobox_inv_6 = new javax.swing.JComboBox<>();
        label_inv_2 = new javax.swing.JLabel();
        combobox_inv_2 = new javax.swing.JComboBox<>();
        label_inv_3 = new javax.swing.JLabel();
        combobox_inv_3 = new javax.swing.JComboBox<>();
        label_inv_4 = new javax.swing.JLabel();
        combobox_inv_4 = new javax.swing.JComboBox<>();
        label_inv_5 = new javax.swing.JLabel();
        combobox_inv_5 = new javax.swing.JComboBox<>();
        label_inv_7 = new javax.swing.JLabel();
        combobox_inv_7 = new javax.swing.JComboBox<>();
        label_inv_8 = new javax.swing.JLabel();
        combobox_inv_8 = new javax.swing.JComboBox<>();
        label_inv_9 = new javax.swing.JLabel();
        combobox_inv_9 = new javax.swing.JComboBox<>();
        label_inv_10 = new javax.swing.JLabel();
        combobox_inv_10 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        SelectPanel = new javax.swing.JPanel();
        label_name = new javax.swing.JLabel();
        label_lvl = new javax.swing.JLabel();
        textfield_name = new javax.swing.JTextField();
        combobox_lvl = new javax.swing.JComboBox<>();
        label_str = new javax.swing.JLabel();
        label_consti = new javax.swing.JLabel();
        label_intelli = new javax.swing.JLabel();
        label_dex = new javax.swing.JLabel();
        label_wis = new javax.swing.JLabel();
        label_charis = new javax.swing.JLabel();
        textfield_str = new javax.swing.JTextField();
        textfield_consti = new javax.swing.JTextField();
        textfield_intelli = new javax.swing.JTextField();
        textfield_dex = new javax.swing.JTextField();
        textfield_wis = new javax.swing.JTextField();
        textfield_charis = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_randomize = new javax.swing.JButton();

        button_new.setText("New");
        button_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_newActionPerformed(evt);
            }
        });

        button_edit.setText("Edit");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_delete.setText("Delete");

        label_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CharcterTemplateNew.jpg"))); // NOI18N

        label_helmet.setText("Helmet");

        combobox_helmet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_weapon.setText("Weapon");

        combobox_weapon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_shield.setText("Shield");

        combobox_shield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_ring.setText("ring");

        combobox_ring.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_belt.setText("Belt");

        combobox_belt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_armour.setText("armor");

        combobox_armor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_boots.setText("boots");

        combobox_boots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_1.setText("Inventory 1");

        combobox_inv_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_6.setText("Inventory 6");

        combobox_inv_6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_2.setText("Inventory 2");

        combobox_inv_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_3.setText("Inventory 3");

        combobox_inv_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_4.setText("Inventory 4");

        combobox_inv_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_5.setText("Inventory 5");

        combobox_inv_5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_7.setText("Inventory 7");

        combobox_inv_7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_8.setText("Inventory 8");

        combobox_inv_8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_9.setText("Inventory 9");

        combobox_inv_9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_inv_10.setText("Inventory 10");

        combobox_inv_10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(label_helmet)
                        .addGap(53, 53, 53)
                        .addComponent(combobox_helmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_weapon)
                            .addComponent(combobox_weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_armour)
                            .addComponent(combobox_armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_boots)
                            .addComponent(combobox_boots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_shield)
                            .addComponent(combobox_shield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ring)
                            .addComponent(combobox_ring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_belt)
                            .addComponent(combobox_belt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_inv_6)
                            .addComponent(label_inv_1))
                        .addGap(34, 34, 34)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combobox_inv_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_inv_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_inv_2)
                            .addComponent(label_inv_7))
                        .addGap(37, 37, 37)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(combobox_inv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(label_inv_3))
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(combobox_inv_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_inv_8)))
                        .addGap(31, 31, 31)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combobox_inv_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_inv_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_inv_4)
                            .addComponent(label_inv_9))
                        .addGap(44, 44, 44)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox_inv_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_inv_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(label_inv_5)
                                .addGap(18, 18, 18)
                                .addComponent(combobox_inv_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DisplayPanelLayout.createSequentialGroup()
                                .addComponent(label_inv_10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_inv_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(label_shield)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_shield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(label_ring)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_ring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(label_belt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_belt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(label_weapon)
                        .addGap(18, 18, 18)
                        .addComponent(combobox_weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(label_armour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(label_boots)
                        .addGap(18, 18, 18)
                        .addComponent(combobox_boots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DisplayPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_helmet)
                            .addComponent(combobox_helmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_inv_1)
                    .addComponent(combobox_inv_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_2)
                    .addComponent(combobox_inv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_3)
                    .addComponent(combobox_inv_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_4)
                    .addComponent(combobox_inv_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_5)
                    .addComponent(combobox_inv_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_inv_6)
                    .addComponent(combobox_inv_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_7)
                    .addComponent(combobox_inv_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_8)
                    .addComponent(combobox_inv_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_9)
                    .addComponent(combobox_inv_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_inv_10)
                    .addComponent(combobox_inv_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );

        jScrollPane2.setViewportView(DisplayPanel);

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addComponent(button_new)
                        .addGap(74, 74, 74)
                        .addComponent(button_edit)
                        .addGap(95, 95, 95)
                        .addComponent(button_delete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_new)
                    .addComponent(button_edit)
                    .addComponent(button_delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        label_name.setText("Name");

        label_lvl.setText("Level");

        combobox_lvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        label_str.setText("Strength");

        label_consti.setText("Constitution");

        label_intelli.setText("Intelligence");

        label_dex.setText("Dexterity");

        label_wis.setText("Wisdom");

        label_charis.setText("Charisma");

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_randomize.setText("Randomize");
        button_randomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_randomizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectPanelLayout = new javax.swing.GroupLayout(SelectPanel);
        SelectPanel.setLayout(SelectPanelLayout);
        SelectPanelLayout.setHorizontalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(button_randomize))
                            .addGroup(SelectPanelLayout.createSequentialGroup()
                                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(SelectPanelLayout.createSequentialGroup()
                                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_consti)
                                            .addComponent(label_str))
                                        .addGap(33, 33, 33)
                                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textfield_consti, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(textfield_str)))
                                    .addGroup(SelectPanelLayout.createSequentialGroup()
                                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SelectPanelLayout.createSequentialGroup()
                                                .addComponent(label_lvl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(combobox_lvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(label_name)
                                            .addComponent(label_intelli))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textfield_intelli, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(textfield_name))))
                                .addGap(18, 18, 18)
                                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SelectPanelLayout.createSequentialGroup()
                                        .addComponent(label_charis)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfield_charis, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addGroup(SelectPanelLayout.createSequentialGroup()
                                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_wis)
                                            .addComponent(label_dex))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textfield_wis)
                                            .addComponent(textfield_dex)))))))
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(button_save)))
                .addGap(40, 40, 40))
        );
        SelectPanelLayout.setVerticalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lvl)
                    .addComponent(combobox_lvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_str)
                    .addComponent(label_dex)
                    .addComponent(textfield_str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_dex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_consti)
                    .addComponent(label_wis)
                    .addComponent(textfield_consti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_wis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_intelli)
                    .addComponent(label_charis)
                    .addComponent(textfield_intelli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_charis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(button_randomize)
                .addGap(134, 134, 134)
                .addComponent(button_save)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(SelectPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_newActionPerformed
        currentChar = new character();

        textfield_name.setText("");
        textfield_charis.setText("");
        textfield_consti.setText("");
        textfield_dex.setText("");
        textfield_intelli.setText("");
        textfield_str.setText("");
        textfield_wis.setText("");

        textfield_charis.setEditable(false);
        textfield_consti.setEditable(false);
        textfield_dex.setEditable(false);
        textfield_intelli.setEditable(false);
        textfield_str.setEditable(false);
        textfield_wis.setEditable(false);

        DisplayPanel.setVisible(true);
        SelectPanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_button_newActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        String[] choices = new String[characterList.size()];
        for (int i = 0; i < characterList.size(); i++) {
            choices[i] = characterList.get(i).name;
        }
        String input = (String) JOptionPane.showInputDialog(null, "Choose item to edit", "Item Select", JOptionPane.QUESTION_MESSAGE, null, choices, choices[0]);

        for (character temp : characterList) {
            if (temp.name.equals(input)) {
                currentChar = temp;
                break;
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_button_editActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        System.out.println(textfield_name.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_randomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_randomizeActionPerformed
        currentChar.randomize();
        // TODO add your handling code here:
    }//GEN-LAST:event_button_randomizeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JPanel SelectPanel;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_new;
    private javax.swing.JButton button_randomize;
    private javax.swing.JButton button_save;
    private javax.swing.JComboBox<String> combobox_armor;
    private javax.swing.JComboBox<String> combobox_belt;
    private javax.swing.JComboBox<String> combobox_boots;
    private javax.swing.JComboBox<String> combobox_helmet;
    private javax.swing.JComboBox<String> combobox_inv_1;
    private javax.swing.JComboBox<String> combobox_inv_10;
    private javax.swing.JComboBox<String> combobox_inv_2;
    private javax.swing.JComboBox<String> combobox_inv_3;
    private javax.swing.JComboBox<String> combobox_inv_4;
    private javax.swing.JComboBox<String> combobox_inv_5;
    private javax.swing.JComboBox<String> combobox_inv_6;
    private javax.swing.JComboBox<String> combobox_inv_7;
    private javax.swing.JComboBox<String> combobox_inv_8;
    private javax.swing.JComboBox<String> combobox_inv_9;
    private javax.swing.JComboBox<String> combobox_lvl;
    private javax.swing.JComboBox<String> combobox_ring;
    private javax.swing.JComboBox<String> combobox_shield;
    private javax.swing.JComboBox<String> combobox_weapon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_armour;
    private javax.swing.JLabel label_belt;
    private javax.swing.JLabel label_boots;
    private javax.swing.JLabel label_charis;
    private javax.swing.JLabel label_consti;
    private javax.swing.JLabel label_dex;
    private javax.swing.JLabel label_helmet;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_intelli;
    private javax.swing.JLabel label_inv_1;
    private javax.swing.JLabel label_inv_10;
    private javax.swing.JLabel label_inv_2;
    private javax.swing.JLabel label_inv_3;
    private javax.swing.JLabel label_inv_4;
    private javax.swing.JLabel label_inv_5;
    private javax.swing.JLabel label_inv_6;
    private javax.swing.JLabel label_inv_7;
    private javax.swing.JLabel label_inv_8;
    private javax.swing.JLabel label_inv_9;
    private javax.swing.JLabel label_lvl;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_ring;
    private javax.swing.JLabel label_shield;
    private javax.swing.JLabel label_str;
    private javax.swing.JLabel label_weapon;
    private javax.swing.JLabel label_wis;
    private javax.swing.JTextField textfield_charis;
    private javax.swing.JTextField textfield_consti;
    private javax.swing.JTextField textfield_dex;
    private javax.swing.JTextField textfield_intelli;
    private javax.swing.JTextField textfield_name;
    private javax.swing.JTextField textfield_str;
    private javax.swing.JTextField textfield_wis;
    // End of variables declaration//GEN-END:variables
}
