package panels;

/**
 * @author SNaKeRUBIN
 */
public class mapEditorMain extends javax.swing.JPanel {

    /**
     * Creates new form mapEditorMain
     */
    public mapEditorMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        SelectPanel = new javax.swing.JPanel();
        label_TT = new javax.swing.JLabel();
        comboBox_TT = new javax.swing.JComboBox<>();
        panel_TT_Container = new javax.swing.JPanel();
        panel_TT_chest = new javax.swing.JPanel();
        label_TT_chest_select = new javax.swing.JLabel();
        combobox_TT_chest_select = new javax.swing.JComboBox<>();
        panel_TT_wall = new javax.swing.JPanel();
        panel_TT_ground = new javax.swing.JPanel();
        panel_TT_character = new javax.swing.JPanel();
        label_TT_charcter_select = new javax.swing.JLabel();
        combobox_TT_charcter_select = new javax.swing.JComboBox<>();
        label_TT_charcter_orientation = new javax.swing.JLabel();
        combobox_TT_charcter_orientation = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label_TT.setText("Tile Type");

        comboBox_TT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        panel_TT_Container.setLayout(new java.awt.CardLayout());

        label_TT_chest_select.setText("Select Item to insert");

        combobox_TT_chest_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_TT_chestLayout = new javax.swing.GroupLayout(panel_TT_chest);
        panel_TT_chest.setLayout(panel_TT_chestLayout);
        panel_TT_chestLayout.setHorizontalGroup(
            panel_TT_chestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TT_chestLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label_TT_chest_select)
                .addGap(36, 36, 36)
                .addComponent(combobox_TT_chest_select, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panel_TT_chestLayout.setVerticalGroup(
            panel_TT_chestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TT_chestLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panel_TT_chestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TT_chest_select)
                    .addComponent(combobox_TT_chest_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        panel_TT_Container.add(panel_TT_chest, "card2");

        javax.swing.GroupLayout panel_TT_wallLayout = new javax.swing.GroupLayout(panel_TT_wall);
        panel_TT_wall.setLayout(panel_TT_wallLayout);
        panel_TT_wallLayout.setHorizontalGroup(
            panel_TT_wallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
        panel_TT_wallLayout.setVerticalGroup(
            panel_TT_wallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        panel_TT_Container.add(panel_TT_wall, "card3");

        javax.swing.GroupLayout panel_TT_groundLayout = new javax.swing.GroupLayout(panel_TT_ground);
        panel_TT_ground.setLayout(panel_TT_groundLayout);
        panel_TT_groundLayout.setHorizontalGroup(
            panel_TT_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
        panel_TT_groundLayout.setVerticalGroup(
            panel_TT_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        panel_TT_Container.add(panel_TT_ground, "card4");

        label_TT_charcter_select.setText("Select Character");

        combobox_TT_charcter_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_TT_charcter_orientation.setText("Character Orientation");

        combobox_TT_charcter_orientation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_TT_characterLayout = new javax.swing.GroupLayout(panel_TT_character);
        panel_TT_character.setLayout(panel_TT_characterLayout);
        panel_TT_characterLayout.setHorizontalGroup(
            panel_TT_characterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TT_characterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_TT_characterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_TT_charcter_select)
                    .addComponent(label_TT_charcter_orientation))
                .addGap(75, 75, 75)
                .addGroup(panel_TT_characterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobox_TT_charcter_orientation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_TT_charcter_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panel_TT_characterLayout.setVerticalGroup(
            panel_TT_characterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TT_characterLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panel_TT_characterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TT_charcter_select)
                    .addComponent(combobox_TT_charcter_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_TT_characterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TT_charcter_orientation)
                    .addComponent(combobox_TT_charcter_orientation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        panel_TT_Container.add(panel_TT_character, "card5");

        javax.swing.GroupLayout SelectPanelLayout = new javax.swing.GroupLayout(SelectPanel);
        SelectPanel.setLayout(SelectPanelLayout);
        SelectPanelLayout.setHorizontalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_TT_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addComponent(label_TT)
                        .addGap(41, 41, 41)
                        .addComponent(comboBox_TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        SelectPanelLayout.setVerticalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TT)
                    .addComponent(comboBox_TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(panel_TT_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(729, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JPanel SelectPanel;
    private javax.swing.JComboBox<String> comboBox_TT;
    private javax.swing.JComboBox<String> combobox_TT_charcter_orientation;
    private javax.swing.JComboBox<String> combobox_TT_charcter_select;
    private javax.swing.JComboBox<String> combobox_TT_chest_select;
    private javax.swing.JLabel label_TT;
    private javax.swing.JLabel label_TT_charcter_orientation;
    private javax.swing.JLabel label_TT_charcter_select;
    private javax.swing.JLabel label_TT_chest_select;
    private javax.swing.JPanel panel_TT_Container;
    private javax.swing.JPanel panel_TT_character;
    private javax.swing.JPanel panel_TT_chest;
    private javax.swing.JPanel panel_TT_ground;
    private javax.swing.JPanel panel_TT_wall;
    // End of variables declaration//GEN-END:variables
}
